const mongoose = require("mongoose");

const EMAIL_PATTERN =
  /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

const emailVerificationSchema =
  new mongoose.Schema(
    {
      fullName: {
        type: String,
        required: [
          true,
          "Full name is required.",
        ],
        trim: true,
        minlength: [
          1,
          "Full name is required.",
        ],
        maxlength: [
          120,
          "Full name cannot exceed 120 characters.",
        ],
      },

      username: {
        type: String,
        required: [
          true,
          "Username is required.",
        ],
        trim: true,
        minlength: [
          1,
          "Username is required.",
        ],
        maxlength: [
          50,
          "Username cannot exceed 50 characters.",
        ],
      },

      email: {
        type: String,
        required: [
          true,
          "Email is required.",
        ],
        lowercase: true,
        trim: true,
        maxlength: [
          254,
          "Email cannot exceed 254 characters.",
        ],
        match: [
          EMAIL_PATTERN,
          "Please enter a valid email address.",
        ],
      },

      /*
       * Stores the bcrypt-hashed registration password.
       * Never store the original password in this collection.
       */
      password: {
        type: String,
        required: [
          true,
          "Password hash is required.",
        ],
      },

      /*
       * Stores the hashed OTP generated by the OTP utility.
       */
      otp: {
        type: String,
        required: [
          true,
          "OTP hash is required.",
        ],
      },

      expiresAt: {
        type: Date,
        required: [
          true,
          "OTP expiration time is required.",
        ],
      },
    },
    {
      timestamps: true,
      versionKey: false,
    }
  );

/*
 * Only one pending verification may exist per email.
 * This also optimizes verification lookups by email.
 */
emailVerificationSchema.index(
  {
    email: 1,
  },
  {
    unique: true,
  }
);

/*
 * MongoDB automatically removes expired verification
 * records after expiresAt has passed.
 */
emailVerificationSchema.index(
  {
    expiresAt: 1,
  },
  {
    expireAfterSeconds: 0,
  }
);

module.exports =
  mongoose.models.EmailVerification ||
  mongoose.model(
    "EmailVerification",
    emailVerificationSchema
  );